services:

  sqlserver:
    build:
      context: ./database
      dockerfile: Dockerfile

    container_name: asisya_sqlserver

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

    environment:
      SA_PASSWORD: "StrongPassw0rd!2026"
      ACCEPT_EULA: "Y"

  api:
    build:
      context: ./asisya_api/asisya_api
      dockerfile: Dockerfile

    container_name: asisya_api

    ports:
      - "5000:8080"

    depends_on:
      - sqlserver


  frontend:
    build:
      context: ./asisya_Frontend
      dockerfile: Dockerfile

    container_name: asisya_frontend

    ports:
      - "3000:80"

    depends_on:
      - api

volumes:
  sql_data: